const KEY = 'S S SUCCESS MISSION_db_v1';
const defaults = { enquiries: [], students: [], attendance: {}, teachers: [{ id: 1, name: 'Class Teacher', role: 'Early Years Educator', qualification: 'Qualified Preschool Educator', bio: 'Warm, patient and activity-focused teacher profile. Update this profile from the admin panel.', photo: '' }], gallery: [{ id: 1, title: 'School Front & Play Area', photo: 'assets/school-front.png' }], settings: { school: 'S S SUCCESS MISSION ', phone: '7079350390', location: 'S S SUCCESS MISSION PARORA CHHAURAHI BEGUSARAI BIHAR PIN 848204', future: 'Build a stronger digital parent experience, enrich activity-based learning, expand teacher development and keep improving our play and learning spaces.' } };
function getDB() { let d = JSON.parse(localStorage.getItem(KEY) || 'null'); if (!d) { d = defaults; localStorage.setItem(KEY, JSON.stringify(d)) } return d } function put(d) { localStorage.setItem(KEY, JSON.stringify(d)); renderAll() }
function login() { if (document.getElementById('loginEmail').value === 'admin@SUCCESS' && document.getElementById('loginPass').value === 'SUCCESS@md') { sessionStorage.setItem('S S SUCCESS MISSION_admin', '1'); document.getElementById('login').classList.add('hidden'); document.getElementById('app').classList.remove('hidden'); renderAll() } else alert('Use the demo credentials shown on the login page.') } function logout() { sessionStorage.removeItem('S S SUCCESS MISSION_admin'); location.reload() }
function showTab(id) { document.querySelectorAll('.tab').forEach(x => x.classList.remove('active')); document.getElementById(id).classList.add('active'); document.querySelectorAll('.side').forEach(x => x.classList.toggle('active', x.dataset.tab === id)); document.getElementById('tabTitle').textContent = id.charAt(0).toUpperCase() + id.slice(1) }
function esc(s = '') { return String(s).replace(/[&<>'"]/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[m])) }
function renderAll() { const d = getDB(); document.getElementById('mEnquiries').textContent = d.enquiries.length; document.getElementById('mStudents').textContent = d.students.length; document.getElementById('mTeachers').textContent = d.teachers.length; const today = new Date().toISOString().slice(0, 10), a = d.attendance[today] || {}, vals = Object.values(a); document.getElementById('mAttendance').textContent = vals.length ? Math.round(vals.filter(x => x === 'Present').length / vals.length * 100) + '%' : '0%'; document.getElementById('dashEnquiries').innerHTML = d.enquiries.slice(0, 5).map(e => `<div class="att-row"><div><b>${esc(e.child)}</b><small> — ${esc(e.parent)} • ${esc(e.program)}</small></div><span class="badge">${esc(e.status)}</span></div>`).join('') || '<p>No enquiries yet. Submit one from the website.</p>'; document.getElementById('enquiryTable').innerHTML = d.enquiries.map(e => `<tr><td>${new Date(e.date).toLocaleDateString()}</td><td>${esc(e.parent)}</td><td>${esc(e.child)}</td><td>${esc(e.age)}</td><td>${esc(e.program)}</td><td>${esc(e.phone)}</td><td><select onchange="setEnquiryStatus(${e.id},this.value)"><option ${e.status === 'New' ? 'selected' : ''}>New</option><option ${e.status === 'Contacted' ? 'selected' : ''}>Contacted</option><option ${e.status === 'Visited' ? 'selected' : ''}>Visited</option><option ${e.status === 'Admitted' ? 'selected' : ''}>Admitted</option></select></td></tr>`).join('') || '<tr><td colspan="7">No enquiries.</td></tr>'; document.getElementById('studentTable').innerHTML = d.students.map((s, i) => `<tr><td>${esc(s.name)}</td><td>${esc(s.parent)}</td><td>${esc(s.age)}</td><td>${esc(s.program)}</td><td>${esc(s.phone)}</td><td><button class="danger" onclick="deleteStudent(${i})">Delete</button></td></tr>`).join('') || '<tr><td colspan="6">No students.</td></tr>'; renderAttendance(); renderTeachersAdmin(); renderGalleryAdmin(); fillSettings() }
function setEnquiryStatus(id, status) { const d = getDB(); const e = d.enquiries.find(x => x.id === id); if (e) e.status = status; put(d) }
function deleteStudent(i) { const d = getDB(); if (confirm('Delete this student?')) { d.students.splice(i, 1); put(d) } }
function renderAttendance() { const d = getDB(); const date = document.getElementById('attendanceDate').value || new Date().toISOString().slice(0, 10); const saved = d.attendance[date] || {}; document.getElementById('attendanceList').innerHTML = d.students.map(s => `<div class="att-row"><div><b>${esc(s.name)}</b><small> — ${esc(s.program)} / ${esc(s.parent)}</small></div><select data-student="${esc(s.name)}"><option ${saved[s.name] === 'Present' ? 'selected' : ''}>Present</option><option ${saved[s.name] === 'Absent' ? 'selected' : ''}>Absent</option></select></div>`).join('') || '<p>Add students first.</p>' }
function saveAttendance() { const d = getDB(), date = document.getElementById('attendanceDate').value || new Date().toISOString().slice(0, 10); d.attendance[date] = {}; document.querySelectorAll('#attendanceList select').forEach(x => d.attendance[date][x.dataset.student] = x.value); put(d); document.getElementById('attendanceMsg').textContent = 'Attendance saved successfully.' }
function renderTeachersAdmin() { const d = getDB(); document.getElementById('teacherAdminGrid').innerHTML = d.teachers.map((t, i) => `<div class="teacher-admin-card"><img src="${t.photo || 'assets/school-front.png'}"><div class="pad"><b>${esc(t.name)}</b><p>${esc(t.role)}</p><small>${esc(t.qualification)}</small><br><button class="danger" onclick="deleteTeacher(${i})">Delete</button></div></div>`).join('') }
function deleteTeacher(i) { const d = getDB(); if (d.teachers.length <= 1) return alert('Keep at least one teacher profile.'); d.teachers.splice(i, 1); put(d) }
function renderGalleryAdmin() { const d = getDB(); document.getElementById('galleryAdminGrid').innerHTML = d.gallery.map((g, i) => `<div class="gallery-admin-card"><img src="${g.photo}"><div class="pad"><b>${esc(g.title)}</b><br><button class="danger" onclick="deleteGallery(${i})">Delete</button></div></div>`).join('') }
function deleteGallery(i) { const d = getDB(); d.gallery.splice(i, 1); put(d) }
function readFile(file) { return new Promise((res, rej) => { const r = new FileReader(); r.onload = () => res(r.result); r.onerror = rej; r.readAsDataURL(file) }) }
function fillSettings() { const d = getDB(), f = document.getElementById('settingsForm'); f.school.value = d.settings.school; f.phone.value = d.settings.phone; f.location.value = d.settings.location; f.future.value = d.settings.future }
function exportData(type) { const d = getDB(); const blob = new Blob([JSON.stringify(d[type], null, 2)], { type: 'application/json' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `S S SUCCESS MISSION-${type}.json`; a.click() }
document.addEventListener('DOMContentLoaded', () => { document.querySelectorAll('.side').forEach(b => b.onclick = () => showTab(b.dataset.tab)); document.getElementById('attendanceDate').value = new Date().toISOString().slice(0, 10); document.getElementById('attendanceDate').addEventListener('change', renderAttendance); document.getElementById('studentForm').addEventListener('submit', e => { e.preventDefault(); const f = new FormData(e.target), d = getDB(); d.students.push({ name: f.get('name'), parent: f.get('parent'), age: f.get('age'), program: f.get('program'), phone: f.get('phone') }); put(d); e.target.reset() }); document.getElementById('teacherForm').addEventListener('submit', async e => { e.preventDefault(); const f = new FormData(e.target), d = getDB(), file = f.get('photo'); d.teachers.push({ id: Date.now(), name: f.get('name'), role: f.get('role'), qualification: f.get('qualification'), bio: f.get('bio'), photo: file && file.size ? await readFile(file) : '' }); put(d); e.target.reset() }); document.getElementById('galleryForm').addEventListener('submit', async e => { e.preventDefault(); const f = new FormData(e.target), d = getDB(), file = f.get('photo'); if (!file || !file.size) return; d.gallery.unshift({ id: Date.now(), title: f.get('title'), photo: await readFile(file) }); put(d); e.target.reset() }); document.getElementById('settingsForm').addEventListener('submit', e => { e.preventDefault(); const f = new FormData(e.target), d = getDB(); d.settings = { school: f.get('school'), phone: f.get('phone'), location: f.get('location'), future: f.get('future') }; put(d); document.getElementById('settingsMsg').textContent = 'Settings saved.' }); if (sessionStorage.getItem('S S SUCCESS MISSION_admin') === '1') { document.getElementById('login').classList.add('hidden'); document.getElementById('app').classList.remove('hidden'); renderAll() } });
